// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import {
  loadDatabaseEnvFiles,
  resolveDatabaseUrl,
} from "./src/lib/database-url";

loadDatabaseEnvFiles();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
