import type { Metadata } from "next";
import { GetUserSession } from "@/app/api/auth/core/session";
import NavigationHeader from "@/components/nav_header";
import NavigationHeaderGate from "@/components/NavigationHeaderGate";
import { SessionUserProvider } from "@/components/providers/SessionUserProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await GetUserSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionUserProvider user={user}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <NavigationHeaderGate>
              <NavigationHeader />
            </NavigationHeaderGate>
            {children}
            <Toaster />
          </ThemeProvider>
        </SessionUserProvider>
      </body>
    </html>
  );
}
